### ISSUE TITLE
Is there some config to make t440s touchpad exactly like macbook?

### ISSUE THREAD

**Issue by siddharthgoel88** [ScottGarman/thinkpad_t440s#3]
Macbook touchpad can detect multiple fingers and have some configuration by default. Do you have some template of that config with which I could make exactly same settings in my Thinkpad t440s?

**Comment by ScottGarman** [comment]
I apologize, I never checked the issues reported to this repository, and it's now years later. I'm not sure if newer Linux distros have better capabilities with this touchpad, but I no longer use a T440s and couldn't confirm it. Closing this issue.
